### ISSUE TITLE
Is it possible to control the simulated robot in gazebo with the Python SDK?

### ISSUE THREAD

**Issue by quanvuong** [xArm-Developer/xArm-Python-SDK#10]
I can see that there is a function ```set_simulation_robot```. Can you please provide more documentation on how to control the simulated robot in gazebo with the Python SDK?

Thank you!

**Comment by DanielWang123321** [comment]
No, if you want use gazebo, please refer to the xArm-ROS
set_simulation_robot is used to simulate robot in xArm Studio.

**Comment by quanvuong** [comment]
Thanks for the clarification!
