### ISSUE TITLE
Persistant balancing/vibration issue.

### ISSUE THREAD

**Issue by EduardoHerrerosMC** [xArm-Developer/xArm-Python-SDK#101]
Hello,

I am having trouble achieving stable balance of the robot xArm lite6 in a given position. I have attached a camera to the TCP with a weight lower than the specified payload. I would need the robot to remain as still as possible in order to capture frames at different given positions. However, it seems that when it reaches the positions, it remains in a continuous state of auto-balancing the weight resulting in visible vibrations that can lead to potential blurred images. I have attempted to calibrate the load of the TCP manually and with the method _iden\_tcp\_load_ but I have not observed any noticeable difference.

Besides, I have notice that some of the joints are not rigid and can be slightly manipulated with the hand, describing small rotation. I was wondering if there was any configuration/state I could set so the joints were kind of 'locked' once the positions were reached, in order to remove this small vibration.

**Comment by MinnaZhong** [comment]
Hi, I think we have already been contacted by Intercom. 

What is the application of Lite6? The motor of Joint 4/5/6 of lite6 is a direct drive motor without a harmonic drive and may not be suitable for your scenario, it is mainly used for education.

What is the SN of your Lite6? You may use xArm6 instead, it uses harmonics in each joint.

Best regards,
