### ISSUE TITLE
Not able to move the 7th joint of xArm7 using set_servo_angle

### ISSUE THREAD

**Issue by M4D-SC1ENTIST** [xArm-Developer/xArm-Python-SDK#104]
Hi. I am developing with xArm7, and I just noticed that the 7th joint malfunctions. whenever I pass in an array with length 7 and servo_id set to 8, or just an angle with servo_id set to 7, the arm cannot execute any command sent by set_servo_angle. When executing `arm.set_servo_angle(servo_id=7, angle=1.57, speed=0.25, wait=False, is_radian=True)
`, the error returned is -10. The arm is mounted on a linear track. Except the 7th joint, every other joint works as expected. I tried it on two xArm7 and it results in the same error, so I think it is unlikely to be a hardware problem. I was wondering is there anything special I need to do in order to operate the 7th joint?

**Comment by M4D-SC1ENTIST** [comment]
Okay, I just connected to a Windows PC and noticed that when the arm is connected with a linear track, it is detected as xArm6 instead of xArm7. But if the arm is connected to a control box directly, it is detected as xArm7. I was wondering if this is some driver issue of the control box that comes with the linear track? If so, how can I fix this?

**Comment by MinnaZhong** [comment]
Hi, We configured the controller of linear motor to work with xArm6 by default. If you use xArm7, you need to reflash the controller's firmware to 7 axes.

Please follow the steps below to reflash the firmware, thank you.
1. Download xarm-tool-gui and the latest offline package in the below link.
2. Launch it, enter IP and click 'connect', after connecting, choose 'xarm7-type7', (choose xarm6-type6 for xarm6), and offline install the firmware again.
3. Reboot the control box, wait 2-3 minutes,  press-down the E-stop button and release to reload the friction parameter.
https://drive.google.com/drive/folders/19Q1mE9i4pSYzLvdO6XdM4nN6RlwTeIOQ?usp=share_link

Best,
