### ISSUE TITLE
State of sdk

### ISSUE THREAD

**Issue by ghost** [xArm-Developer/xArm-Python-SDK#11]
Hi there
Just wanted to ask since I am thinking of buying an xarm whether the python sdk is comparable to the c++, Ros or direct programming of the controller in terms of latency, full API support etc.?

Thank you and kind regards

**Comment by vimior** [comment]
The most complete SDK of the xarm project is the Python SDK, and ROS uses the C++ SDK directly.
Thank you and kind regards
