### ISSUE TITLE
End force sensor

### ISSUE THREAD

**Issue by lorepieri8** [xArm-Developer/xArm-Python-SDK#12]
Is the end force sensor referred [here](https://github.com/xArm-Developer/xArm-Python-SDK/blob/master/example/wrapper/common/8001-force_tech.py) included in the arm or is it an external sensor?

**Comment by vimior** [comment]
An external sensor hung on the end independently developed by our company.
Thank you

**Comment by mfkenson** [comment]
can i use read the force sensor via this SDK and control the arm via ROS moveit ?

**Comment by penglongxiang** [comment]
For more information of xArm with force/torque sensor, please check [here](https://www.ufactory.cc/products/ufactory-xarm-7-with-6-axis-force-torque-sensor).

**Comment by penglongxiang** [comment]
@mfkenson As force sensor is a new add-on feature, its interfaces are available as python SDK for now, ROS support will be ready later.
