### ISSUE TITLE
Velocity control breaks `realtime_joint_speeds`

### ISSUE THREAD

**Issue by joshuafishman** [xArm-Developer/xArm-Python-SDK#18]
In velocity control mode, the values in `XArmAPI.realtime_joint_speeds` seem to be constant. This is despite the robot's velocity obviously changing in response to velocity commands sent via `vc_set_joint_velocity`. 

The constant values in our case are `[-0.0001913145970320329, -8.029435412026942e-05, -0.0003226289991289377, -5.9169465203012805e-06, 0.00039677994209341705, 0.000555296428501606, 0.0]`, but I assume there's nothing significant about these.

Is there another way to get the current joint velocities in velocity control mode?

**Comment by MinnaZhong** [comment]
The problem has been fixed, xArmAPI.realtime_joiont_speeds can be used in each mode, the update frequency is 5HZ.
Firmware and xArmStudio requirements: V1.8.5.

Issue closed.
