### ISSUE TITLE
Gripper hangs in velocity control

### ISSUE THREAD

**Issue by joshuafishman** [xArm-Developer/xArm-Python-SDK#19]
This script (in which `arm` is an instance of `XArmAPI`) hangs indefinitely:

    ...
    arm.clear_warnings_errors()
    arm.motion_enable(enable=True)
    arm.set_mode(4)
    arm.set_collision_sensitivity(3)
    arm.set_state(0)

    code, pos = arm.get_gripper_position()
    arm.set_gripper_position(pos)
    ...

Without the call to `set_gripper_position` it does not hang. The infinite loop is in this [line](https://github.com/xArm-Developer/xArm-Python-SDK/blob/e8475781cb7365a3d4134fdda0ee359b6142ca8e/xarm/x3/gripper.py#L213) in the SDK. It looks like it's hanging because the arm state has been silently reset to 1 (sleep), so the loop [here](https://github.com/xArm-Developer/xArm-Python-SDK/blob/e8475781cb7365a3d4134fdda0ee359b6142ca8e/xarm/x3/base.py#L2020) runs forever.

Is it possible to use the gripper in velocity mode?

**Comment by vimior** [comment]
Hi @joshuafishman , you can set the parameter wait_motion to False to skip the state detection of the robotic arm.
`set_gripper_position(pos, wait_motion=False)`

**Comment by joshuafishman** [comment]
The remaining issues seem to have been a result of modifying the collision setpoint, which seems to silently reset the robot to position mode.

**Comment by vimior** [comment]
Hi @joshuafishman 
Setting the collision sensitivity will modify the state of the robotic arm, but will not modify the mode.
If an error is raised, it is possible to modify the mode not in the position mode.

**Comment by MinnaZhong** [comment]
The problem has been fixed on  SDK V1.8.4.
Recommend updating the firmware and xArmStudio to V1.8.3 to test.

Issue closed.
