### ISSUE TITLE
Is there a way to test your code offline in simulation without a connection to the robot?

### ISSUE THREAD

**Issue by Olimoyo** [xArm-Developer/xArm-Python-SDK#23]
Hi,

Is there a way to test the code we write using the Python SDK in simulation? 

Would that only be available with the ROS interface and Gazebo? 

Thanks

**Comment by vimior** [comment]
At present, the use of SDK must be connected to the control box, but no
virtual mode (set_simulation_robot) can be set (the real machine will not
move at this time, and the simulated movement can be seen through the
studio)

Oliver Limoyo ***@***.***> 于2021年11月25日周四 上午4:19写道：

**Comment by Olimoyo** [comment]
I see, thanks!
