### ISSUE TITLE
set_joints_torque

### ISSUE THREAD

**Issue by 1seck** [xArm-Developer/xArm-Python-SDK#26]
hi there,

how can i set the torque for the xarm? when i enter "set_joints_torque" the respond will be

> [SDK][ERROR][2022-04-07 07:54:22][base.py:338] - - API -> set_joints_torque -> code=3, joints_torque=[0, 0, 0, 0, 0, 0, 0]

no matter which mode i choose?

**Comment by vimior** [comment]
@1seck 

Hello, can you provide the firmware version and SDK version you are using? After using this interface, get a look at the error code and warning code.

**Comment by vimior** [comment]
@1seck 
Sorry, I confirmed that this function is not supported, this interface is only reserved before.

**Comment by 1seck** [comment]
ok thx
