### ISSUE TITLE
Move commands ignoring some or all parameters / skipping the command

### ISSUE THREAD

**Issue by zpjester** [xArm-Developer/xArm-Python-SDK#30]
I am attempting to run basic move functions on an xArm 6, however some of the functions I am calling appear to not work correctly or at all. Calling `move_gohome()` does nothing regardless of the parameters; the arm stays in place. Calling `set_servo_cartesian()` ignores the velocity and acceleration provided as parameters, and moves with max speed and acceleration, usually causing it to (falsely) detect a collision due to the high jerk. The full program I attempted to run is attached below.
```python
import sys
import math
import time
import datetime
import random
import traceback
import threading
import armLib

try:
    from xarm.tools import utils
except:
    pass
from xarm import version
from xarm.wrapper import XArmAPI

def pprint(*args, **kwargs):
    try:
        stack_tuple = traceback.extract_stack(limit=2)[0]
        print('[{}][{}] {}'.format(time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time())), stack_tuple[1], ' '.join(map(str, args))))
    except:
        print(*args, **kwargs)

pprint('xArm-Python-SDK Version:{}'.format(version.__version__))

arm = XArmAPI('192.168.1.207', baud_checkset=False)
arm.clean_warn()
arm.clean_error()
arm.motion_enable(True)
arm.set_mode(1)
arm.set_state(0)
time.sleep(1)


angles = [0, 0, -45, 0, 0, 0]

code = arm.move_gohome(speed = 100, mvacc = 100)
print(code)
time.sleep(1)
pose = [307, 0, 112, 180, 0, 0]
code = arm.set_servo_cartesian(pose, speed=100, mvacc=100, mvtime=1)
print(code)
time.sleep(2)
pose = [307, 100, 112, 180, 0, 0]
code = arm.set_servo_cartesian(pose, speed=100, mvacc=100, mvtime=1)
print(code)

time.sleep(5)
```

**Comment by penglongxiang** [comment]
Hi, `move_gohome()` will only work in position control mode (Mode 0). `set_servo_cartesian()` will work in SERVO mode (Mode 1) which means it is for real-time streaming or tracking purpose, the last received command will be executed immediately, the command should be updated step-by-step in high frequency. The speed/acceleration are reserved parameters in this function, and will not take effect.

In your application where the target changes 100 mm in y direction, you should switch to **Mode 0** and use `set_position()` instead. Target speed and acceleration can be specified here.
