### ISSUE TITLE
Feature Request: Track Lifetime Hours on Robot

### ISSUE THREAD

**Issue by scottrpaterson** [xArm-Developer/xArm-Python-SDK#38]
It would be nice to be able to see how many lifetime hours are on the robot arm.

For most industrial equipment this is a standard feature.

**Comment by TonyLeheng** [comment]
Do you mean the entire lifetime of robot arm, or a software feature to count the work hours since the robot was born?

**Comment by scottrpaterson** [comment]
Thank you for the reply. The number of hours that the robot has been powered on / used. This is useful like a cars odometer.

ABB robots call this a "Duty Time Counter"

Fanuc calls this "Working Hours" - https://www.robot-forum.com/robotforum/thread/13526-r-30ia-working-hours/

**Comment by MinnaZhong** [comment]
Hi,

Thanks, Scott, close this ticket and we will consider it in the future.
