### ISSUE TITLE
Xarm 6 Lite - Initial Pose settings lost on reboot

### ISSUE THREAD

**Issue by scottrpaterson** [xArm-Developer/xArm-Python-SDK#39]
If you reboot or power off the system, these settings are lost.

![Capture1](https://user-images.githubusercontent.com/11578353/188700985-66d496f3-c3dc-4364-ae21-70d2229bc41f.PNG)

**Comment by MinnaZhong** [comment]
Hi, Please provide the firmware and xArmStudio version. Can you reproduce it everytime?
