### ISSUE TITLE
xArm 6 - C19 - End Module Communication Error

### ISSUE THREAD

**Issue by scottrpaterson** [xArm-Developer/xArm-Python-SDK#42]
I'm getting a lot of C19 - End Module Communication Error with the xArm Gripper.

How can this issue be fixed?

**Comment by vimior** [comment]
Hi, @scottrpaterson 
Can you describe your use case?
- How to use C19 is more likely to appear?
- Can C19 be eliminated by software or interface?

**Comment by scottrpaterson** [comment]
Thank you for the reply, @vimior 

- C19 seems to happen when moving the real robot around.
- It can be temporary fixed by changing the robots position.
- When the error happens I get "End Module Communication Error" in the studio and I cannot move the gripper.

I am guessing that maybe the internal wiring is damaged? This robot does not have many hours.

**Comment by MinnaZhong** [comment]
Hi, please provide the SN of the xArm and gripper.

You can control the gripper when the robot is not moving, right?
It seems that C19 only occurs in specific positions. Can you provide a video to show us the problem?

Best,
