### ISSUE TITLE
Velocity control mode acceleration

### ISSUE THREAD

**Issue by BugLight** [xArm-Developer/xArm-Python-SDK#43]
Greetings!
How can I control acceleration in velocity control mode?
I use `vc_set_cartesian_velocity` method to set target velocity. But it seems that arm gains speed very slowly.
I have already tried `set_tcp_maxacc` method and nothing changed.

Looking for your help!

**Comment by penglongxiang** [comment]
Hi, if `set_tcp_maxacc` still can not make a difference, I suppose it would be the **jerk** (derivative of acceleration) being low (for stable and smooth transition), however, its value for velocity mode is fixed currently, we will test and increase it in next controller firmware updates. May I know what is your target linear velocity and expected time to reach it?

**Comment by BugLight** [comment]
> Hi, if `set_tcp_maxacc` still can not make a difference, I suppose it would be the **jerk** (derivative of acceleration) being low (for stable and smooth transition), however, its value for velocity mode is fixed currently, we will test and increase it in next controller firmware updates. May I know what is your target linear velocity and expected time to reach it?

Thank you for your answer!
Maximum possible acceleration and jerk would be the best in our case .
We would expect the arm to stop completely within ~40 ms. Sure, maximum speed to meet this requirement depends on maximum acceleration possible.
If jerk and acceleration could be configured in velocity control mode just like in position control mode we would really appreciate that!

**Comment by penglongxiang** [comment]
We are in the process of optimizing it, could you tell us 40ms is from what velocity to decelerate and stop? I think it is relatively harsh for a high speed. 

Will `set_state(4)` directly be suitable for your case?
