### ISSUE TITLE
How to correctly set IP, router, broadcast and DNS addresses

### ISSUE THREAD

**Issue by febert** [xArm-Developer/xArm-Python-SDK#44]
Hi,

In order to be able to communicate with the xarm while having internet connectivity, I need to change the IP address of the xarm.

I was wondering if it is also necessary to change the Broadcast address, the router address and the DNS1 address to reflect my local network's address range (it is 192.168.0.1 - 192.168.255), for example my desktop has 192.168.0.47.

My xarm has the following network configuration:
![Screenshot from 2022-10-14 14-26-06](https://user-images.githubusercontent.com/12017064/195946588-76d6fa00-b0db-4866-b4a0-ae5ac66e25eb.png)

My router is at 192.168.0.1
My /etc/resolv.con says that my DNS server is: nameserver 127.0.0.53

Are the following changes correct and necessary?:
IP to  192.168.0.100 (my choice)
Broadcast to 192.168.0.255
Routers to 192.168.0.1
and
DNS1 to 127.0.0.53

Thanks a lot!

**Comment by MinnaZhong** [comment]
Hi , As discussed in the email, please modify the network segment of PC to t192.168.1.xxx first. After connecting with our control box, you can change the IP of the control box to whatever you want.
