### ISSUE TITLE
How to Set Position of Elbow for Xarm7

### ISSUE THREAD

**Issue by febert** [xArm-Developer/xArm-Python-SDK#45]
Hi,

For my application I need to control the position of the elbow of my xarm7 to avoid collisions with the environment.

Is there any way I can bias the IK solution to a desired elbow configuration?
I couldn't find any parameter for the in the API.

Thanks!

**Comment by MinnaZhong** [comment]
Sorry, currently the redundant degree of freedom is not supported.
You may need to use third-party libs to avoid obstacles, like Moveit...
