### ISSUE TITLE
Question about the get_servo_angle function

### ISSUE THREAD

**Issue by swiz23** [xArm-Developer/xArm-Python-SDK#5]
Hi,

I'm coming over here from your ROS packages. While there, I was told that you can only reliably get the servo joint positions at a max rate of 5Hz. Is that the case with the get_servo_angle function here as well? Otherwise, what is the max rate I can reliably call this function?

**Comment by penglongxiang** [comment]
Theoretically, the maximum update rate is 250 Hz. However, constantly querying at high frequency might have influence on the real time performance of robot. We suggest to call at <=100Hz  or use controller port 30003 for 100Hz automatic reporting.
