### ISSUE TITLE
unlimited gripper speed problem

### ISSUE THREAD

**Issue by HoneyMack** [xArm-Developer/xArm-Python-SDK#56]
Hello,
I'm using this sdk for controlling gripper, and it seems to me that [set_gripper_speed](https://github.com/xArm-Developer/xArm-Python-SDK/blob/56905c7726d70d32278632e766de20b18e6eb8b0/xarm/wrapper/xarm_api.py#L1730) doesn't have any speed limitation whereas [xarm_ros api](https://github.com/xArm-Developer/xarm_ros/blob/c10d5e59dd50109d15e8fbd3da0bae6aeacbb855/xarm_api/src/xarm_driver.cpp#L1150-L1153) has.

The gripper speed can be set to exceeded number, which we think caused damages on our gripper (making some noise from it).

Thank you.

**Comment by MinnaZhong** [comment]
Hi

Thanks for the suggestion, We will add it in python SDK, it should be 0-5000.
