### ISSUE TITLE
Control GPIO of Control Box

### ISSUE THREAD

**Issue by Akumar201** [xArm-Developer/xArm-Python-SDK#57]
Hi, I am currently creating a gripper with proximity sensor. I want to set the Control Box GPIO high when something is near to the proximity sensor. I got an Idea that using set_cgpio_digital I can do so. However, my doubt is the robotic arm is also connected to my laptop. I wanted to know do I need to establish connection from the raspberry pi on the end effector having sensor or I can directly do so using the provided cable in the box. 

![image](https://user-images.githubusercontent.com/108360879/211383805-473cb238-a6ff-4bf8-9108-1349cb608791.png)

**Comment by MinnaZhong** [comment]
Hi Akumar,

You can directly do the connection using the provided cable, when there is a signal from the end-effector IO, setting the controller  GPIO to high.
For your reference: http://help.ufactory.cc/en/articles/4721853-how-to-use-third-party-equipment-on-ufactory-xarm

Best regards,
Minna

**Comment by Akumar201** [comment]
Hi, Thank you for your response, I would like to know that how can I buy more of these cables that was provided with the robot.

![image](https://user-images.githubusercontent.com/108360879/211383805-473cb238-a6ff-4bf8-9108-1349cb608791.png)

**Comment by MinnaZhong** [comment]
Hi Akumar,

 May I know why you want more of this cable? There is only one IO connector at the robot end, and each robot comes with one such cable by default. What is your application?

Best regards,
Minna

**Comment by Akumar201** [comment]
Hi, I want another cable such that I can experiment with different customized grippers. Is there a way I can buy those? Thank You

**Comment by MinnaZhong** [comment]
Hi, please email <minna.zhong@ufactory.cc >， and I will provide the invoice to you.  The cable is 20 USD,  how many cables do you want? Where are you located? The shipping fee is around 50USD.

**Comment by Akumar201** [comment]
Thank You, I will do that.
