### ISSUE TITLE
Add feature to move xArm 7 down in Z axis untill it finds the bottom

### ISSUE THREAD

**Issue by Niekvdplas** [xArm-Developer/xArm-Python-SDK#62]
Hi, is there a feature or a chain of commands how I can move the suction cup all the way down in the Z-axis until it knows it is on the floor. I can do this when picking something up from the floor via the feedback received from the suction cup, but when putting something down I am not sure how to get feedback that the arm gradually reached the floor.

**Comment by vimior** [comment]
@Niekvdplas 
There is no such detection at present, and it is more reliable to add a torque sensor.
