### ISSUE TITLE
How to know the current cmd when I set wait=False

### ISSUE THREAD

**Issue by chendiqi02** [xArm-Developer/xArm-Python-SDK#7]
I sent a sequence of joint angles using set_servo_angle() with wait=False.
In the same time, I would like to scynchornize xarm with other devices. 
So, is it possible to know which cmd is in action during the arm's motion in this situation?
Thanks a lot!

**Comment by zfls** [comment]
Hello,
Do you add the end tool to the xarm?
Please describe the device you want to use in detail, thanks.

**Comment by zfls** [comment]
Hello,
Do you add the end tool to the xarm?
Please describe the device you want to use in detail, thanks.
You can send an email to my email: shiyanfei@ufactory.cc. Then I will receive your news in time.
