### ISSUE TITLE
Discrepancy in rotation reported by `get_position()` method and xArm studio

### ISSUE THREAD

**Issue by moshestanylov** [xArm-Developer/xArm-Python-SDK#87]
There is a noticeable difference between the rotation reported by the `get_position()` method and the rotation displayed in the xArm studio UI.

position reported by sdk
```
code, [x, y, z, roll, pitch, yaw]
0 [627.548096, -150.436432, 317.392456, -179.974466, -7.762547, 19.99617]
```

position reported by xArm studio
![Screenshot from 2023-06-26 11-40-44](https://github.com/xArm-Developer/xArm-Python-SDK/assets/108144720/2ca88add-ce55-4904-b60d-75799c93e0ac)

**Comment by MinnaZhong** [comment]
Hi @moshestanylov 

Please enter 'Settings-General-Assistive Features-Orientation Control', and choose R/P/Y for get_position.
For Axis-angle, you should use get_position_aa.

![image](https://github.com/xArm-Developer/xArm-Python-SDK/assets/43405238/51f16289-21f0-4007-9621-ba5ab14a9d8a)

**Comment by moshestanylov** [comment]
Thanks for the clarification
