### ISSUE TITLE
How to interpret the error and warn code

### ISSUE THREAD

**Issue by quanvuong** [xArm-Developer/xArm-Python-SDK#9]
When I command to the robot to move to a position, I received these messages in the terminal:

[SDK][ERROR][2021-06-05 20:27:06][base.py:1524] - - list index out of range
[SDK][WARNING][2021-06-05 20:27:06][base.py:1225] - - ReportDataException: length=0, data_len=233, state=0, mode=0, collis_sens=0, teach_sens=0, error_code=95, warn_code=62
servo_error_code, servo_id=1, status=219, code=15
servo_error_code, servo_id=2, status=73, code=64

How should I interpret these messages?

**Comment by DanielWang123321** [comment]
We did not define code=64, it may caused by network, did you use WiFi to control the robot? You can ping the robot IP for a while to check the network status.
