### ISSUE TITLE
What is state 5 

### ISSUE THREAD

**Issue by alonks1234** [xArm-Developer/xArm-Python-SDK#90]
What is the meaning of state = 5 on the xarm6? 

States 1 - 4 are documented but not 5. Thanks!

**Comment by penglongxiang** [comment]
Hi，state 5 is MODE_CHANGE, meaning the robot mode has changed or some system configuration has changed, which will influence the planning and execution afterwards, so under this state, the previous sent command will be cleared if not yet executed, like in state 4 (STOP). 

By the way, you may also see state 6 (DECEL_STOP), which means the robot is in the process of deceleration stop.

**Comment by penglongxiang** [comment]
You may also check our latest [user manual](https://www.ufactory.cc/wp-content/uploads/2023/05/xArm-User-Manual-V2.0.0.pdf) in page 204.
