### ISSUE TITLE
 xARM 6 Lite Python SDK change of initial joint position

### ISSUE THREAD

**Issue by emanuelgollob** [xArm-Developer/xArm-Python-SDK#99]
Hello, 
I am using the latest Python SDK to control an xARM 6 Lite in joint online trajectory planning mode (Github example 2006-joint_online_trajectory_planning.py).

Whenever I start the Python script, the arm approaches the [0,0,0,0,0,0,0] joint position before the first motion command. 
Is there a way to get rid of this pre-command motion or change the [0,0,0,0,0,0,0] position to any other joint position?

I tried to set the “Initial Position” Joints Position in Web GUI settings>motions>parameters - it didn´t have any effect.
In the Python SDK, there is an arm.set_initial_point([0, 0, 180, 0, 0, 0, 0]) function - but didn´t have any effect either.

Any help is very much appreciated!

**Comment by penglongxiang** [comment]
Please comment out or delete the line:
`arm.reset(wait=True)`

This will command the robot to go to **all zero** joint position.

**Comment by emanuelgollob** [comment]
Thanks a lot, that worked!
